### ISSUE TITLE
Example hello.c program doesn't work

### ISSUE THREAD

**Issue by alog243** [tsarpaul/llvm-string-obfuscator#2]
Decode stub checks for null byte before decoding to determine the end of a string. If compiler puts two strings together in the string table without any padding between them, a string will get decoded multiple times.

I ran into this issue with the given hello.c program. 'hello world %d' and '%s' were placed together without any space between. Since the encoded null byte 0x01 wasn't decoded, the decoder bled into the '%s' string and decoded it with the 'hello world %d' string, and then decoded it _again_ afterwards. This caused printf to receive '$r' instead of '%s' and failed to print how much I love bananas.

Easy fix: change the cmp in decode stub to check for 0x01 instead of 0x00 to end string.

**Comment by alog243** [comment]
I originally misread the code, but it's still behaving as I described, just in a different way.

inside the decode function, the previous character (at [RDI - 0x1]) is modified, and then if the *current* character is null, it stops decoding. The problem is that the null terminator byte is encoded, so it will fall through to the next string as described above. The better solution is to just act on the current character instead of doing this weird offset -1 thing that actually breaks it.

**Comment by tsarpaul** [comment]
Hi, thanks for the issue, I think I worked on some different settings so I missed this issue. The fix is simple but I'm looking to replace the manual LLVM construction of the Decode function with loading it dynamically (through independent LLVM bitcode) so I hopefully fix it shortly.

**Comment by alog243** [comment]
Now that I've actually learned what PHI and GEP instructions are, the fix for this particular issue is super easy. Just have to change line 91 in StringObfuscator.cpp to:

`auto cmp = Builder->CreateICmpEQ(sub, ConstantInt::get(IntegerType::get(Ctx, 8), 0), "cmp");`

That way it checks for the current character to be null, rather than the next character, still encoded (which has been stored in var2 already).

**Comment by tsarpaul** [comment]
Fixed, thanks!
