### ISSUE TITLE
Unable to make project

### ISSUE THREAD

**Issue by gladys95a** [tsarpaul/llvm-string-obfuscator#4]
Hi, I am trying to make this project but encounter the following errors:

[ 50%] Building CXX object StringObfuscator/CMakeFiles/LLVMStringObfuscator.dir/StringObfuscator.o
/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp: In function ‘llvm::Function* {anonymous}::createDecodeStubFunc(llvm::Module&, std::vector<{anonymous}::GlobalString*>&, llvm::Function*)’:
/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:31:2: error: ‘FunctionCallee’ was not declared in this scope
  FunctionCallee DecodeStubCallee = M.getOrInsertFunction("decode_stub",
  ^~~~~~~~~~~~~~
/llvm/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:33:44: error: ‘DecodeStubCallee’ was not declared in this scope
  Function *DecodeStubFunc = cast<Function>(DecodeStubCallee.getCallee());
                                            ^~~~~~~~~~~~~~~~
/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:33:44: note: suggested alternative: ‘DecodeStubFunc’
  Function *DecodeStubFunc = cast<Function>(DecodeStubCallee.getCallee());
                                            ^~~~~~~~~~~~~~~~
                                            DecodeStubFunc
/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:47:78: error: no matching function for call to ‘llvm::IRBuilder<>::CreateStructGEP(llvm::GlobalVariable*&, unsigned int&)’
    auto *String = Builder.CreateStructGEP(GlobString->Glob, GlobString->index);
                                                                              ^
In file included from /llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:7:0:
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1365:10: note: candidate: llvm::Value* llvm::IRBuilder<T, Inserter>::CreateStructGEP(llvm::Type*, llvm::Value*, unsigned int, const llvm::Twine&) [with T = llvm::ConstantFolder; Inserter = llvm::IRBuilderDefaultInserter]
   Value *CreateStructGEP(Type *Ty, Value *Ptr, unsigned Idx,
          ^~~~~~~~~~~~~~~
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1365:10: note:   candidate expects 4 arguments, 2 provided
/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:49:43: error: no matching function for call to ‘llvm::IRBuilder<>::CreateCall(llvm::Function*&, <brace-enclosed initializer list>)’
    Builder.CreateCall(DecodeFunc, {StrPtr});
                                           ^
In file included from /llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:7:0:
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1663:13: note: candidate: llvm::CallInst* llvm::IRBuilder<T, Inserter>::CreateCall(llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&, llvm::MDNode*) [with T = llvm::ConstantFolder; Inserter = llvm::IRBuilderDefaultInserter]
   CallInst *CreateCall(Value *Callee, ArrayRef<Value *> Args = None,
             ^~~~~~~~~~
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1663:13: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘llvm::ArrayRef<llvm::Value*>’
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1670:13: note: candidate: llvm::CallInst* llvm::IRBuilder<T, Inserter>::CreateCall(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&, llvm::MDNode*) [with T = llvm::ConstantFolder; Inserter = llvm::IRBuilderDefaultInserter]
   CallInst *CreateCall(FunctionType *FTy, Value *Callee,
             ^~~~~~~~~~
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1670:13: note:   candidate expects 5 arguments, 2 provided
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1679:13: note: candidate: llvm::CallInst* llvm::IRBuilder<T, Inserter>::CreateCall(llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, const llvm::Twine&, llvm::MDNode*) [with T = llvm::ConstantFolder; Inserter = llvm::IRBuilderDefaultInserter]
   CallInst *CreateCall(Value *Callee, ArrayRef<Value *> Args,
             ^~~~~~~~~~
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1679:13: note:   candidate expects 5 arguments, 2 provided
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1688:13: note: candidate: llvm::CallInst* llvm::IRBuilder<T, Inserter>::CreateCall(llvm::Function*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&, llvm::MDNode*) [with T = llvm::ConstantFolder; Inserter = llvm::IRBuilderDefaultInserter]
   CallInst *CreateCall(Function *Callee, ArrayRef<Value *> Args,
             ^~~~~~~~~~
/usr/lib/llvm-6.0/include/llvm/IR/IRBuilder.h:1688:13: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘llvm::ArrayRef<llvm::Value*>’
/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp: In function ‘llvm::Function* {anonymous}::createDecodeFunc(llvm::Module&)’:
/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:61:2: error: ‘FunctionCallee’ was not declared in this scope
  FunctionCallee DecodeFuncCallee = M.getOrInsertFunction("decode",
  ^~~~~~~~~~~~~~
/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:64:40: error: ‘DecodeFuncCallee’ was not declared in this scope
  Function *DecodeFunc = cast<Function>(DecodeFuncCallee.getCallee());
                                        ^~~~~~~~~~~~~~~~
/llvm-string-obfuscator/StringObfuscator/StringObfuscator.cpp:64:40: note: suggested alternative: ‘DecodeFunc’
  Function *DecodeFunc = cast<Function>(DecodeFuncCallee.getCallee());
                                        ^~~~~~~~~~~~~~~~
                                        DecodeFunc
StringObfuscator/CMakeFiles/LLVMStringObfuscator.dir/build.make:62: recipe for target 'StringObfuscator/CMakeFiles/LLVMStringObfuscator.dir/StringObfuscator.o' failed
make[2]: *** [StringObfuscator/CMakeFiles/LLVMStringObfuscator.dir/StringObfuscator.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'StringObfuscator/CMakeFiles/LLVMStringObfuscator.dir/all' failed
make[1]: *** [StringObfuscator/CMakeFiles/LLVMStringObfuscator.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can advise? Thanks!

**Comment by tsarpaul** [comment]
Try add 
```#include "llvm/IR/DerivedTypes.h"```

To StringObfuscator.c

Let me know if that reduces the amount of errors.

**Comment by gladys95a** [comment]
hi, thanks for the fast reply. after adding, no changes to the errors

**Comment by tsarpaul** [comment]
I was using LLVM-11 to build the project, it's probably related (I see you are using LLVM-6).
I'll have to check wherever I can backport it.

**Comment by gladys95a** [comment]
thanks for the info, i have upgrade my llvm and it works!
